name: Delete Branch After Merge (Except Release Branches)

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete branch if it is not a release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          echo "Branch name: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^release/[0-9]{2}\.[0-9]{2}\.[0-9]{2}-v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Deleting branch $BRANCH_NAME..."
            git push origin --delete "$BRANCH_NAME"
          else
            echo "Branch $BRANCH_NAME is a release branch. Skipping deletion."
          fi