name: Code Quality Check Action

on:
  pull_request:

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ['pint']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install PHP Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run ${{ matrix.task }}
        run: ./vendor/bin/pint --test
